version: "3.3"

services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/app/config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  server:
    build: server/.
    command: bash -c "sleep 20; cd /code/app/; npm run dev;"
    ports:
      - 5000:5000
    links:
      - db:db
    # volumes:
    #   - ./server/app:/code/app
    #   - /code/app/node_modules
    env_file:
      - server/.env
    restart: on-failure


  front:
    build: front/.
    ports:
      - 3000:3000
    links:
      - server:server
    restart: on-failure


volumes:
  db_data: {}
